

name: Scrape nfl player data

on:
  workflow_dispatch:
  schedule:
    - cron: '17 0 * * *'

jobs:
    scheduled:
      runs-on: ubuntu-latest
      steps:
          - name: Check out nfl players data from 1999 to present.
            uses: actions/checkout@v2
          - name: Download data
            run: |-
              for i in {1999..2021};
              do
                wget -O https://github.com/nflverse/nflfastR-data/blob/master/data/player_stats/player_stats_$i.csv.gz > data/player_stats_$i.csv.gz;
              done

          - name: Commit and push data files
            run: |-
              git config user.name "Automated"
              git config user.email "actions@users.noreply.github.com"
              git add -A
              timestamp=$(date -u)
              git commit -m "Latest data: ${timestamp}" || exit 0
              git push